#!/bin/bash
sudo apt update &&
  sleep 10s &&
  sudo apt -y install apt-transport-https &&
  sleep 10s &&
  sudo apt -y install ca-certificates &&
  sleep 10s &&
  sudo apt -y install curl &&
  sleep 10s &&
  sudo apt -y install software-properties-common &&
  sleep 10s &&
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
  sleep 10s &&
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" &&
  sleep 10s &&
  sudo apt update &&
  sleep 10s &&
  apt-cache policy docker-ce &&
  sleep 10s &&
  sudo apt -y install docker-ce &&
  sleep 10s &&
  sudo systemctl start docker
