#!/bin/bash
until [[ -f /var/lib/cloud/instance/boot-finished ]]; do
  sleep 1
done
sudo add-apt-repository ppa:certbot/certbot --yes
sudo apt-get update --yes
sudo apt-get install python-certbot-nginx --yes
cd /etc/nginx/sites-available
sed -i 's/server_name _;/server_name agge.dev www.agge.dev;/g' default
sudo nginx -t
sudo service nginx reload
sudo certbot --nginx -d agge.dev -d www.agge.dev --non-interactive --agree-tos -m augustalexandersson@gmail.com
. /configure/milestone_3
