#!/usr/bin/env bash
sudo apt-get install unzip &&
  wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip &&
  unzip terraform_0.12.18_linux_amd64.zip &&
  sudo mv terraform /usr/local/bin/ &&
  sudo rm terraform_0.12.18_linux_amd64.zip &&
  cd ../infrastructure &&
  terraform init
